name: ukl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  http: ^0.13.5
  flutter_inappwebview: ^6.1.5
  youtube_player_flutter: ^9.1.1
  image_picker: ^1.0.4
  path: ^1.8.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
